version: '3.4'
services:
  base-image:
    container_name: BI-feb-27th
    build:
      context: .
      args:
        UN: jlovick
    entrypoint: /usr/bin/bash -c  /usr/local/bin/entrypoint.sh 

    stdin_open: true
    tty: true
    ports:
            - "22:22"


