version: '3.4'
services:
  base-image:
    container_name: BI-feb-28th
    image: base-image/bi:latest
    build:
      context: .
      args:
        UN: jlovick
    entrypoint: /usr/bin/bash -c  /usr/local/bin/entrypoint.sh 
    stdin_open: true
    tty: true
    ports:
            - "2222:22"
    volumes:
      - "$HOME/code:/mnt/host:rw"
